При запуске ошибка: «AttributeError: partially initialized module 'brain_games' has no attribute 'StartingTheGam(most likely due to a circular import)»